DEBUG = false
NODES = []

[API]
TOKEN_ID = ""
TOKEN_SECRET = ""
NODE_URL = ""

[API_HANDLERS]
TICKET = "/api2/json/access/ticket"
VERSION = "/api2/json/version"
STATUS = "/api2/json/nodes/${TARGETNODE}/status"
HA_GROUPS = "/api2/json/cluster/ha/groups"

[CLI_COMMANDS]
VERSION = "echo pvesh get /version"
HA_GROUPS = "echo pvesh get /cluster/ha/groups"

