DEBUG = false
NODES = []

[API]
TOKEN_ID = ""
TOKEN_SECRET = ""
BASE_URL = ""
ENTRY_POINT = "/api2/json"
VERIFY_SSL = true

[CLI]
ENTRY_POINT = "pvesh"

[SSH]
HOSTNAME = ""
USERNAME = ""
PASSWORD = ""
PORT = 22
AGENT = false
KEY_FILENAME = ""

#[API_HANDLERS]
#TICKET = "/api2/json/access/ticket"
#VERSION = "/api2/json/version"
#STATUS = "/api2/json/nodes/{TARGETNODE}/status"
#HA_GROUPS = "/api2/json/cluster/ha/groups"
#
#[CLI_COMMANDS]
#VERSION = "pvesh get /version"
##VERSION = "sleep 5"
#HA_GROUPS = "pvesh get /cluster/ha/groups"
#HA_GROUPS_CREATE = "pvesh create /cluster/ha/groups --group={NAME} --nodes={NODES} --comment={COMMENT} --nofailback={NOFAILBACK} --restricted={RESTRICTED}"


