DEBUG = false
NODES = []

[API]
TOKEN_ID = ""
TOKEN_SECRET = ""
BASE_URL = ""
ENTRY_POINT = "/api2/json"
VERIFY_SSL = true

[CLI]
ENTRY_POINT = "pvesh"

[SSH]
HOSTNAME = ""
USERNAME = ""
PASSWORD = ""
PORT = 22
AGENT = false
KEY_FILENAME = ""

[SCENARIOS]
MAX_CONCURRENCY = 10



