API:
  backend: "https"
Scenarios:
  SequenceScenarios:
    file: "sequence_scenarios"
    config:
        name: "Scenario {id}"
        file: "clone_template_vm"
        variables:
          destination_nodes: "all-online"
          destination_vm_id_start: 400
          destination_vm_id_increment: 1
          network:
            ip_start: "192.0.2.0/24"
            ip_increment: 1
          replications:
            nodes:
              - "{destination_node|-1}"
              - "{destination_node|+1}"
          ha:
            group:
              name: "gr-{destination_node|-1}-{destination_node}f-{destination_node|+1}"
              nodes: "{destination_node|-1}:80,{destination_node}:100,{destination_node|+1}:60"
