API:
  backend: "https"
Scenarios:
  CloneTemplateVM:
    file: "clone_template_vm"
    config:
      node: "c01"
      destination_node: "c02"
      source_vm_id: 1004
      destination_vm_id: 201
      overwrite_destination: True
      name: "Cloned01"
      network:
        ip: "192.0.2.1/24"
        increase_ip: 1
      tags: ["tag1", "dot-{vm_dot_ip}","{vm_ip}"]
      full: 1
